=== SassanAsnaashari/6Semester/Internettechnoligien/Praktikum1/vl1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT ITT (Name*, Datum? ,img*,Beschreibung)>
    <!ELEMENT Name (Vorname, Nachname+)*>
    <!ELEMENT Vorname (#PCDATA)>
    <!ELEMENT Nachname (#PCDATA)>
    <!ELEMENT Datum (#PCDATA)>
    <!ELEMENT img EMPTY >
    <!ATTLIST img src CDATA #REQUIRED>
    <!ELEMENT hoehe (#PCDATA) >
    <!ELEMENT Beschreibung (#PCDATA|Name|Vorname)*>
    <!ENTITY VL "Vorlesung Internettechnologie">
    <!ENTITY  %String "(#PCDATA)">

=== SassanAsnaashari/6Semester/Internettechnoligien/Praktikum1/AllesImDok.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE ITT SYSTEM "vl1.dtd">

<ITT>
    <Name>
        <Vorname>Hans</Vorname>
        <Nachname>Peter</Nachname>
    </Name>
    <Datum> 05.04.2022 </Datum>
    <img src="Test"/>
    <Beschreibung>
        beliebige Zeichen
        <Name>
            <Vorname> &VL; Vorname</Vorname>
            <Nachname>Nachname</Nachname>
        </Name>
        Weiterer Text
    </Beschreibung>
</ITT>
