=== SassanAsnaashari/6Semester/Internettechnoligien/Praktikum2/BPML.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Preisübersicht (Tankstelle+, Pächter+, Mineralölgesellschaft+, Options)>
    <!ELEMENT Tankstelle (Name, Adresse, Geodaten*, Beschreibung*, Preise)>
        <!ELEMENT Name (#PCDATA) >
        <!ELEMENT Adresse (#PCDATA)>
        <!ELEMENT Geodaten (#PCDATA)>
        <!ELEMENT Beschreibung (#PCDATA)>
        <!ELEMENT Preise (Preis)*>
            <!ELEMENT Preis (#PCDATA)>
            <!ATTLIST Preis kraftstoffart (E10| Super| Diesel| SuperPlus)>

        <!ATTLIST Tankstelle PächterID IDREF #REQUIRED>
        <!ATTLIST Tankstelle MineralölgesellschatsID IDREF #REQUIRED>
        <!ATTLIST Tankstelle Bewertung (1|2|3|4|5|6)*>

    <!ELEMENT  Pächter ( Name | Adresse | #PCDATA)*>
        <!ATTLIST Pächter pächterID ID #REQUIRED>

    <!ELEMENT Mineralölgesellschaft (Name, Adresse, Mailadresse) >
        <!ELEMENT Mailadresse (#PCDATA)>
        <!ATTLIST Mineralölgesellschaft mineralId ID #REQUIRED>

    <!ELEMENT Options (ANY)* >

=== SassanAsnaashari/6Semester/Internettechnoligien/Praktikum2/bpml.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Preisübersicht SYSTEM "BPML.dtd">

<Preisübersicht>
    <Tankstelle PächterID="2" MineralölgesellschatsID="34" Bewertung="3">
        <Name> Shell </Name>
        <Adresse>Luipoldstraße 289, 84029 LA</Adresse>
        <Geodaten>23.4123, 23.4267</Geodaten>
        <Beschreibung> Ein tolle Tankstelle im Herzen Landshut</Beschreibung>
        <Preise>
            <Preis kraftstoffart="Diesel"> 1.78</Preis>
            <Preis kraftstoffart="E10"> 1.90</Preis>
            <Preis kraftstoffart="Super"> 2.20</Preis>
        </Preise>
    </Tankstelle>
    <Pächter pächterID="2">
        <Name> Peter </Name> ist der Pächter und wohnt <Adresse>Luipoldstraße 5</Adresse> über der Tankstelle
    </Pächter>
    <Mineralölgesellschaft mineralId="34">
        <Name>Shell</Name>
        <Adresse>Suhrenkamp 71 - 77 22335 Hamburg</Adresse>
        <Mailadresse>kontakt@shell.com</Mailadresse>
    </Mineralölgesellschaft>
    <Options>
        Zusatzadresse:
            <Adresse>Zweite Adresse</Adresse>
    </Options>
</Preisübersicht>
